sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - fonts-ipafont
script:
#  mvn clean verify
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
cache:
  directories:
    - $HOME/.m2
